username: #**************
password: #*************

#url can include the job_type,location,salary filter from linkedIn search
url: 'https://www.linkedin.com/jobs/search/?currentJobId=3566989713&f_JT=F&geoId=103644278&keywords=electrical%20engineer&location=United%20States&refresh=true'

total_pages : 38